### ISSUE TITLE
Feat : ADD MUSEUM IN GALLERY WITH THEIR INFO

### ISSUE THREAD

**Issue by AbhinaySngh** [Webaddicted91/Visieum2.0#29]
![image](https://github.com/user-attachments/assets/788b2438-1bc0-4e46-9d91-6b66f4a2bc01)

**Comment by AbhinaySngh** [comment]
@Webaddicted91 Please assign me this issue under gssoc-ext or hectober label.

**Comment by rounakdey6** [comment]
i want to work on this project ,please assign to me

**Comment by Khushi-Nigam** [comment]
I can build beautiful gallery for this project please assign this to me .

**Comment by Webaddicted91** [comment]
@Khushi-Nigam @AbhinaySngh @rounakdey6 Try to add Indian museum , I will merge the best one

**Comment by rounakdey6** [comment]
@Webaddicted91 you didn't wait for my action.

**Comment by rounakdey6** [comment]
https://github.com/user-attachments/assets/39e75c79-83f8-4c8e-803b-46a842ebd316

@Webaddicted91 please have a look

**Comment by rounakdey6** [comment]
@Webaddicted91 i just merge it , it is just for few minute

**Comment by rounakdey6** [comment]
@Webaddicted91 after judging all of the work , if you have merged other's pr . it won't be problematic
