### ISSUE TITLE
Missing "Show Password" Icon and Low Visibility of Text on Login Form

### ISSUE THREAD

**Issue by PATILYASHH** [Webaddicted91/Visieum2.0#83]
#### Description
- The login form is missing a "Show Password" icon, making it difficult for users to verify their input while typing passwords.
- The text overlay on the image in the login section is not easily visible due to the contrast between the text color and the background image, reducing readability.

#### Steps to Reproduce
1. Navigate to the login form.
2. Notice there is no "Show Password" icon in the password field.
3. View the text overlay on the image; it is not clearly visible.

#### Expected Behavior
- A "Show Password" icon (such as an eye icon) should be present in the password field, allowing users to toggle between showing and hiding the password.
- The text on the image should be more legible, either by changing the text color or applying a background shadow or overlay for better contrast.

#### Possible Solution
1. **Show Password Icon**: Add a toggle icon (eye icon) to the password field that switches the input type between `password` and `text`.
2. **Text Visibility**: Improve the contrast of the text on the image by:
   - Changing the text color to a darker or more visible shade.
   - Adding a shadow or background overlay behind the text to make it stand out against the image.

#### Screenshot
![image](https://github.com/user-attachments/assets/93c25c31-4c85-44bf-94c9-dc1b5c4b34ac)

#### Additional Context
Enhancing these two elements will improve both the usability and design of the login form, making it more user-friendly and visually appealing.

**Comment by Lokesh11868** [comment]
Could you please assign me this issue under Gssoc'24 ext. ?

**Comment by PATILYASHH** [comment]
Please assign me this issue
